### ISSUE TITLE
Plugin via template not run in npp

### ISSUE THREAD

**Issue by lutz** [kbilsted/NotepadPlusPlusPluginPack.Net#43] opened 2019-01-09 10:20 UTC
Hello,

I installed the template, but can't get the plugin to run inside NPP. I use the current Windows 10 x64 Pro version with NPP x86 (v7.6.2). The plugin (as generated by the template without any adjustments) is built correctly under `%PROGRAMDATA%\Notepad++\plugins\`. However, it is neither displayed in the plugin admin nor the commands anywhere else within NPP.
Best regards

P.S: The same behaviour with the x64 version of npp

**Comment by kbilsted** [comment] 2019-01-09 15:13
Can you try a release of notepad from around jan 2018 ?

**Comment by lutz** [comment] 2019-01-10 09:20
With the Jan18 Version it seems to be loaded but the Unicode problem show up:

![grafik](https://user-images.githubusercontent.com/26437097/50958593-60fdcc00-14c1-11e9-9625-699a7d3bbf76.png)

**Comment by kbilsted** [comment] 2019-01-16 21:22
can't really tell you why

**Comment by kbilsted** [comment] 2019-04-10 21:15
@jokedst  any input?

**Comment by mahee96** [comment] 2020-07-29 20:22
Hi @lutz , I was wondering why was the plugin present in "%PROGRAMDATA%\Notepad++\plugins\" ?, isn't it supposed to be in %PROGRAMFILES%\..\? for it to be loaded by the Notepad++ plugin manager. Was there any reason behind it.

@lutz @kbilsted The second issue seems like an outdated assembly of "mscorlib.dll" being referenced in the project. Is this due to the Project_config/Assembly_config using .NET framework "lower" than the one supported by Notepad++(does npp use CLR libs?)  which could be the reason for incompatibility.

If there is still an issue, probably checking the Properties->Application->Target_Framework to be .NET framework 4.0 or above and doing a build could resolve the issue with unsupported mscorlib.dll

The ANSI plugin issue might have been resolved by the latest release NppPlugin0.94.00.zip (Jan 18 build) as I couldn't reproduce the issue.

Happy to help,
Thanks

**Comment by kbilsted** [comment] 2020-07-30 19:31
@mahee96 thanks for your input. Haven't looked at the project for a while. Do you have the time to fiddle with improvements?

**Comment by mahee96** [comment] 2020-07-30 19:54
@kbilsted sure, I would be happy to contribute.

**Comment by kbilsted** [comment] 2020-08-02 12:03
@mahee96 at some point N++ moved the folder for plugins, we haven't updated this plugin pack accordingly.

**Comment by mahee96** [comment] 2020-08-14 18:27
The master branch contains the latest fixes and the ANSI plugin issue has been resolved. 
If there is still an issue we can re-open it or track it with a new issue anytime. 

Closing this issue for now :)

**Closed by mahee96** 2020-08-14 18:27 UTC
