### ISSUE TITLE
MyNpp.dll is not compatible with the current version of Notepad++.

### ISSUE THREAD

**Issue by miaoweiwei** [kbilsted/NotepadPlusPlusPluginPack.Net#51] opened 2019-05-15 13:45 UTC
MyNpp.dll is not compatible with the current version of Notepad++.

**Comment by kbilsted** [comment] 2019-05-15 18:19
ty for reporting. can you please provide steps to reproduce and error message

**Comment by miaoweiwei** [comment] 2019-05-16 01:05
I used VS2017, the version of Notepad++ is 7.6.6, only used this template without adding any code.
![](https://i.imgur.com/hEjb2fU.jpg)

**Comment by miaoweiwei** [comment] 2019-05-16 01:06
> ty报告。可以请你提供重现和错误信息的步骤

![360截图20190516085948917](https://user-images.githubusercontent.com/20410007/57819174-dc49f400-77b9-11e9-985d-0b85a0f87646.jpg)

**Comment by miaoweiwei** [comment] 2019-05-18 02:24
> ty for reporting. can you please provide steps to reproduce and error message

Dumpbin has only three definitions exported from the DLL, respectively
  2 0 00039FB6 getFuncsArray
  4 1 00000000 getName
  0 2 00039FAA isUnicode

I am using the VS2017 Chinese version, my computer is win10，谢谢啦

**Comment by Panhectic** [comment] 2019-08-18 11:03
I found the same problem when I first tried the template.
It is, by default, building a 64bit DLL - that caused this message with a 32bit NPP.
I chose to upgrade my NPP to 64bit and everything was fine.

**Comment by joylin1984** [comment] 2019-10-10 17:15
@miaoweiwei 请问你解决了吗，我也发现了这个问题呢。

**Comment by kbilsted** [comment] 2019-10-13 18:24
We probably need to import the npp definitions and do a new release. Anyone up for the task? there are python scripts in this repo to import the npp files

**Comment by miaoweiwei** [comment] 2019-11-24 00:40
> @miaoweiwei 请问你解决了吗，我也发现了这个问题呢。

没有解决

**Comment by Wrastone** [comment] 2020-02-26 13:24
Any updates for this issue? because i have same trouble. Tried countless times in many variations of versions and platforms: VS 2015/2017 and npp 7.8.4 both 32 and 64 bit, nothing works, everytime get an error like @miaoweiwei

**Comment by mahee96** [comment] 2020-07-29 10:12
@kbilsted I can volunteer for this as I am currently working with similar task using this plugin. 
@Wrastone and @miaoweiwei can you please provide the combinations that you guys tried, such as NPP version (type x86/x64?), Plugin Template Version (was is a release zip or did you build this VS template from source by yourself).

**Comment by kbilsted** [comment] 2020-08-14 15:26
@mahee96 vote to close - I think the latest PR should solve or people can re-open.

**Comment by mahee96** [comment] 2020-08-14 19:00
Yeah, looks like it. **Closing with some notes**.

**Just a note:** This issue happened to me when I was doing changes in Cpp/Win32 Api world. 
The reason for my problem was that the getFuncsArray method wasn't returning a valid function pointer array/vector or the nbF value which should be a valid count entries in the function pointer array/vector.

_So Ensure proper value to_
1. **nbF** - Count of function pointers in the vector/array
2. **return pointer** (to array/vector of function pointers)

Definition in: **_\PluginInfrastructure\UnmanagedExports.cs_**
```
        [DllExport(CallingConvention = CallingConvention.Cdecl)]
        static IntPtr getFuncsArray(ref int nbF)
        {
            nbF = PluginBase._funcItems.Items.Count;
            return PluginBase._funcItems.NativePointer;
        }
```

**Closed by mahee96** 2020-08-14 19:00 UTC
