### ISSUE TITLE
Project Template not recognized in Visual Studio 2022

### ISSUE THREAD

**Issue by glanham-jr** [kbilsted/NotepadPlusPlusPluginPack.Net#86] opened 2022-04-15 20:01 UTC
I tried loading the using the latest release (0.95) with Visual Studio 2022, but the IDE didn't recognize it. It currently works with Visual Studio 2019. However, I was able to create the project in Visual Studio 2019, and open it in 2022.

**Comment by kbilsted** [comment] 2022-05-28 14:50
If you can, please submit a PR that fixes it:)

**Comment by eladkarako** [comment] 2022-06-08 23:53
same for 2019 even.

**Comment by kbilsted** [comment] 2022-06-09 06:47
What is the errors you are getting and what are the solutions to those errors?

**Comment by eladkarako** [comment] 2022-06-09 13:32
> errors

can't remember if I even saw any.
afterwards I've just cloned someone's else repo, whom made use of this template,  
since I've wanted to see if NPP can even use it.  

it does not seems that the C# is even working.  
the .net dll lacks entry points and won't recognised with NPP.

seems a lot have changed both in the structure of NPP and VS.

switched to VCPP. it uses sendmessage, a lot nastier, but compiles and working.

**Comment by TaoK** [comment] 2022-08-04 07:31
Insofar as I'm experiencing the same thing (and I haven't tried VS2019 yet), there are no errors to report:
* You place the Zip file in `Documents\Visual Studio 2022\Templates\ProjectTemplates\Visual C#\` as suggested
* You open Visual Studio
* You search for the template - it's not there

(I've also tried something more equivalent to another template that does work, eg unzipped in `C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\ProjectTemplates\CSharp\1033`, but same outcome)

Presumably there's a failure in a log somewhere, but I have no idea where the template enumeration log might be found.

**Comment by TaoK** [comment] 2022-08-06 13:39
Presumably this is unrelated information, but when I installed VS2019 as a workaround, I found that I was still missing a few steps that were non-obvious (to me):
* I had to install at least the C# support in Visual Studio, otherwise the template was ignored / didn't show up
* I had to install the .Net 4 targeting pack, otherwise I couldn't compile the new project
* I had to install .Net 3.5 (windows optional feature), otherwise the DllExportTask wouldn't run

After all this I was able to create the project in VS2019, compile it successfully, and also open and run/compile in VS2022.

**Comment by mahee96** [comment] 2022-11-17 20:21
so basically the csproj definition incompatibility or missing dependencies for VS2022 issue.

will take care of it in new release's regression testing closing issue.

**Closed by mahee96** 2022-11-17 20:21 UTC

**Comment by kbilsted** [comment] 2022-11-17 21:04
@mahee96 why close bug before committing changes to the project file?

**Comment by mahee96** [comment] 2022-11-18 05:28
@kbilsted, I am working on synchronizing the latest Scintilla.iface API and current state of this plugin APIs by testing custom generator script which will include all the changes that are directly embedded into the generated CS files. 

I just wanted to see what are the active open items that the upcoming PR won't be fixing, so closed the issues that will be fixed.
